# Generated by Django 4.1.2 on 2023-01-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PopularWeb', '0002_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='name',
            new_name='productname',
        ),
    ]
