# Generated by Django 4.1.2 on 2022-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PopularOpticsApp', '0006_rename_size_prodb_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodb',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
