# Generated by Django 4.1.2 on 2023-01-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PopularOpticsApp', '0008_adminpgdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodb',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
