# Generated by Django 4.1.2 on 2023-01-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PopularOpticsApp', '0009_alter_prodb_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminpgdb',
        ),
    ]
