# Generated by Django 4.1.2 on 2023-01-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PopularOpticsApp', '0010_delete_adminpgdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
