# Generated by Django 4.1.2 on 2023-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PopularOpticsApp', '0011_staffdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
