# Generated by Django 4.1.2 on 2023-01-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PopularOpticsApp', '0013_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='estimatedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
